AWSTemplateFormatVersion: "2010-09-09"
Description: "Deploy a service"
Parameters:
  AppEnv:
    Type: String
    Default: dev
    Description: The environment profile the app will be deployed in
  AppName:
    Type: String
    Default: alinefinancial
    Description: The application name
  ServiceName:
    Type: String
    Description: The service name
  ServicePort:
    Type: Number
    Description: The service port number
  CommitHash:
    Type: String
    Description: Hash of the most recent code commit (This is the tag for the container)
Resources:

  # MicroService
  MicroService:
    Type: AWS::ECS::Service
    DependsOn: ApiListener
    Properties:
      ServiceName: !Sub '${AppName}-${AppEnv}-${ServiceName}'
      Cluster: !Sub '{{resolve:secretsmanager:${AppName}/${AppEnv}/secrets/resources:SecretString:ClusterName}}'
      TaskDefinition: !Ref ServiceTask
      DeploymentConfiguration:
        MinimumHealthyPercent: 100
        MaximumPercent: 200
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Sub '{{resolve:secretsmanager:${AppName}/${AppEnv}/secrets/resources:SecretString:PrivateSubnetA}}'
            - !Sub '{{resolve:secretsmanager:${AppName}/${AppEnv}/secrets/resources:SecretString:PrivateSubnetB}}'
          SecurityGroups:
            - !Sub '{{resolve:secretsmanager:${AppName}/${AppEnv}/secrets/resources:SecretString:SecurityGroup}}'
      LoadBalancers:
        - ContainerName: !Sub '${AppName}-${AppEnv}-${ServiceName}'
          ContainerPort: !Ref ServicePort
          TargetGroupArn: !Ref ServiceTargetGroup


  # Task Definition for the MicroService
  ServiceTask:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${AppName}-${AppEnv}
      RequiresCompatibilities:
        - FARGATE
      Memory: 2048
      Cpu: 512
      NetworkMode: awsvpc
      ExecutionRoleArn: !Sub '{{resolve:secretsmanager:${AppName}/${AppEnv}/secrets/resources:SecretString:TaskExecutionRole}}'
      TaskRoleArn: !Sub '{{resolve:secretsmanager:${AppName}/${AppEnv}/secrets/resources:SecretString:ContainerExecutionRole}}'
      ContainerDefinitions:
        - Name: !Sub ${AppName}-${AppEnv}-${ServiceName}
          Image: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${AppName}/${AppEnv}/${ServiceName}:${CommitHash}'
          PortMappings:
            - ContainerPort: !Ref ServicePort
          Environment:
            - Name: APP_PORT
              Value: !Ref ServicePort
            - Name: APP_USER_ACCESS_KEY
              Value: !Sub '{{resolve:secretsmanager:${AppName}/${AppEnv}/secrets/user-credentials:SecretString:ACCESS_KEY}}'
            - Name: APP_USER_SECRET_KEY
              Value: !Sub '{{resolve:secretsmanager:${AppName}/${AppEnv}/secrets/user-credentials:SecretString:SECRET_KEY}}'
            - Name: ENCRYPT_SECRET_KEY
              Value: !Sub '{{resolve:secretsmanager:${AppName}/${AppEnv}/secrets/user-credentials:SecretString:EncryptKey}}'
            - Name: JWT_SECRET_KEY
              Value: !Sub '{{resolve:secretsmanager:${AppName}/${AppEnv}/secrets/user-credentials:SecretString:JWTSecretKey}}'
            - Name: PORTAL_LANDING
              Value: http://alinefinancial.com
            - Name: PORTAL_DASHBOARD
              Value: http://dashboard.alinefinancial.com
            - Name: PORTAL_ADMIN
              Value: http://admin.alinefinancial.com
            - Name: DB_USERNAME
              Value: !Sub '{{resolve:secretsmanager:${AppName}/${AppEnv}/secrets/db:SecretString:Username}}'
            - Name: DB_PASSWORD
              Value: !Sub '{{resolve:secretsmanager:${AppName}/${AppEnv}/secrets/db:SecretString:Password}}'
            - Name: DB_HOST
              Value: !Sub '{{resolve:secretsmanager:${AppName}/${AppEnv}/secrets/db:SecretString:Address}}'
            - Name: DB_PORT
              Value: !Sub '{{resolve:secretsmanager:${AppName}/${AppEnv}/secrets/db:SecretString:Port}}'
            - Name: DB_NAME
              Value: !Sub '{{resolve:secretsmanager:${AppName}/${AppEnv}/secrets/db:SecretString:Database}}'
          Essential: true
          Memory: 2048
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub ${AppName}/${AppEnv}/${ServiceName}
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: !Sub ${ServiceName}-${AppEnv}
              awslogs-create-group: 'true'

  # The TargetGroup for the MicroService
  ServiceTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: !Ref ServicePort
      HealthCheckIntervalSeconds: 60
      HealthCheckPath: '/health'
      HealthCheckTimeoutSeconds: 5
      HealthCheckPort: !Ref ServicePort
      Protocol: HTTP
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: '60'
      TargetType: ip
      VpcId: !Sub '{{resolve:secretsmanager:${AppName}/${AppEnv}/secrets/resources:SecretString:VpcId}}'

  # API Listener
  ApiListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Sub '{{resolve:secretsmanager:${AppName}/${AppEnv}/secrets/resources:SecretString:ServiceALB}}'
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ServiceTargetGroup
      Port: !Ref ServicePort
      Protocol: HTTP

